name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: ls -l 
      - name: data1
        run: echo '${{ contains(toJson(github.event.commits.*.message)), '#skip') }}'
      - name: data2
        run: echo '${{ toJson(github.event.commits.*.message) }}'
      - name: data3
        run: echo '${{ github.event.commits.*.message }}'
