name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    concurrency: deploy-group
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install --fix
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Run flyctl deploy --remoter-only
        run: flyctl deploy --remote-only
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        
